/*
  CONTENT.JS — generated by admin.html
  Upload this file into the js/ folder of your GitHub repo, replacing the old one.
*/

const SITE_CONTENT = {
  "site": {
    "name": "Moshiur <i><span style=\"color:#d357fe\"><span style=\"color:#e392fe\">Masud</span></span></i>",
    "initials": "MMR",
    "tagline": "Anatomist, Educator & Researcher",
    "footerNote": {
      "en": "Built with <i><span style=\"font-family:'Unbounded', sans-serif\"><span style=\"font-family:'Righteous', sans-serif\"><span style=\"color:#53d5fd\">curiosity</span></span></span></i>. Updated regularly.",
      "bn": "<i><span style=\"font-family:'Righteous', sans-serif\">কৌতূহল</span></i> নিয়ে তৈরি। নিয়মিত আপডেট হয়।"
    },
    "theme": "cyber-violet",
    "fontPreset": "theme-default",
    "sectionStyles": {
      "home": {
        "font": "theme-default",
        "color": "theme-default"
      },
      "about": {
        "font": "theme-default",
        "color": "theme-default"
      },
      "publications": {
        "font": "theme-default",
        "color": "theme-default"
      },
      "apps": {
        "font": "theme-default",
        "color": "theme-default"
      },
      "journey": {
        "font": "theme-default",
        "color": "theme-default"
      },
      "testimonials": {
        "font": "theme-default",
        "color": "theme-default"
      },
      "blog": {
        "font": "theme-default",
        "color": "theme-default"
      },
      "gallery": {
        "font": "theme-default",
        "color": "theme-default"
      },
      "faq": {
        "font": "theme-default",
        "color": "theme-default"
      },
      "contact": {
        "font": "theme-default",
        "color": "theme-default"
      }
    },
    "defaultLang": "en",
    "whatsapp": "8801914128747",
    "gaId": "",
    "seoDescription": "Dr. Md. Moshiur Rahman — Associate Professor of Anatomy, medical educator, and researcher based in Khulna, Bangladesh.",
    "socialImage": "images/profile.svg",
    "sectionVisibility": {
      "about": true,
      "publications": true,
      "apps": true,
      "journey": true,
      "testimonials": true,
      "blog": true,
      "gallery": true,
      "faq": true,
      "contact": true
    },
    "sectionOrder": [
      "about",
      "journey",
      "publications",
      "testimonials",
      "blog",
      "gallery",
      "apps",
      "faq",
      "contact"
    ],
    "feedbackFormEndpoint": "",
    "customFonts": [
      {
        "name": "Syncopate"
      }
    ]
  },
  "nav": [
    {
      "label": {
        "en": "Home",
        "bn": "হোম"
      },
      "href": "#home"
    },
    {
      "label": {
        "en": "About",
        "bn": "সম্পর্কে"
      },
      "href": "#about"
    },
    {
      "label": {
        "en": "Publications",
        "bn": "প্রকাশনা"
      },
      "href": "#publications"
    },
    {
      "label": {
        "en": "Apps",
        "bn": "অ্যাপস"
      },
      "href": "#apps"
    },
    {
      "label": {
        "en": "Journey",
        "bn": "যাত্রা"
      },
      "href": "#journey"
    },
    {
      "label": {
        "en": "Testimonials",
        "bn": "মতামত"
      },
      "href": "#testimonials"
    },
    {
      "label": {
        "en": "Blog",
        "bn": "ব্লগ"
      },
      "href": "#blog"
    },
    {
      "label": {
        "en": "Gallery",
        "bn": "গ্যালারি"
      },
      "href": "#gallery"
    },
    {
      "label": {
        "en": "FAQ",
        "bn": "প্রশ্নোত্তর"
      },
      "href": "#faq"
    },
    {
      "label": {
        "en": "Contact",
        "bn": "যোগাযোগ"
      },
      "href": "#contact"
    }
  ],
  "hero": {
    "eyebrow": {
      "en": "Portfolio",
      "bn": "পোর্টফোলিও"
    },
    "name": "Moshiur Rahman",
    "role": {
      "en": "MS (Anatomy) — Associate Professor, Ad-din Akij Medical College",
      "bn": "এমএস (এনাটমি) — সহযোগী অধ্যাপক, আদ-দ্বীন আকিজ মেডিকেল কলেজ"
    },
    "tagline": {
      "en": "Enthusiastic anatomist with a research-oriented mindset — specialized in histology, plastination, and genetic laboratory techniques.",
      "bn": "গবেষণামুখী মানসিকতাসম্পন্ন একজন উৎসাহী এনাটমিস্ট — হিস্টোলজি, প্লাস্টিনেশন ও জেনেটিক ল্যাবরেটরি কৌশলে বিশেষ প্রশিক্ষণপ্রাপ্ত।"
    },
    "ctaLabel": {
      "en": "Get in touch",
      "bn": "যোগাযোগ করুন"
    },
    "ctaIcon": "→",
    "ctaHref": "#contact",
    "photo": "images/profile.svg",
    "status": {
      "en": "Physician | Educator | Techy",
      "bn": "চিকিৎসক | শিক্ষক | প্রযুক্তি-প্রেমী"
    },
    "badges": [
      {
        "icon": "🔬",
        "label": "Anatomist"
      },
      {
        "icon": "🎓",
        "label": "Educator"
      },
      {
        "icon": "🧬",
        "label": "Researcher"
      }
    ]
  },
  "cv": {
    "dataUrl": "",
    "name": ""
  },
  "about": {
    "heading": {
      "en": "About",
      "bn": "সম্পর্কে"
    },
    "paragraphs": [
      "I am an Associate Professor of Anatomy at Ad-din Akij Medical College, with a research-oriented mindset and expertise in research methodology and biostatistics.",
      "As a dedicated educator and curriculum thinker, I have specialized training in histology, plastination, embalming, and genetic laboratory techniques — including DNA extraction, gene amplification, and primer designing.",
      "Earlier in my career I also worked as a Medical Officer managing indoor and outdoor pediatric cases. This site brings together my academic background, publications, and professional journey — feel free to reach out."
    ],
    "photo": "images/about.svg",
    "stats": [
      {
        "value": "10+",
        "label": "Years in Medicine"
      },
      {
        "value": "13+",
        "label": "Publications"
      },
      {
        "value": "4",
        "label": "Institutions"
      }
    ],
    "credentials": [
      "MS (Anatomy) — Bangabandhu Sheikh Mujib Medical University, 2020",
      "MBBS — Jahurul Islam Medical College, Dhaka University, 2012",
      "BMDC Registration: A 66165"
    ]
  },
  "publications": {
    "heading": {
      "en": "Publications",
      "bn": "প্রকাশনা"
    },
    "subheading": {
      "en": "Research papers",
      "bn": "গবেষণাপত্র"
    },
    "categories": [
      {
        "id": "research",
        "label": "Research Papers",
        "items": [
          {
            "title": "Histomorphological Pattern of Different Type of Breast Lesion in a Medical College Hospital in Bangladesh",
            "journal": "J Army Med Coll Jashore, 7(1), 5–10",
            "year": "2026",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Evaluation of Palpable Breast Lesions by Fine Needle Aspiration Cytology in A Tertiary Medical College Hospital",
            "journal": "Mediscope, 12(1), 34–38",
            "year": "2025",
            "link": "https://doi.org/10.3329/mediscope.v12i1.79894",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Trends in Addressing Different Cognitive Domains in SAQs of Anatomy Paper-I Written Examination Held Under Rajshahi Medical University",
            "journal": "Journal of Ad-Din Akij Medical College, 3(1), 18–22",
            "year": "2024",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Histopathological Diagnosis of Gastric Biopsies in Correlation with Endoscopy in Bangladeshi People",
            "journal": "Journal of Ad-Din Akij Medical College, 2(2), 25–30",
            "year": "2023",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "The Positions and Directions of the Mental Foramina of Dry Mandibles in Bangladesh",
            "journal": "Journal of Ad-Din Akij Medical College, 2(2), 10–14",
            "year": "2023",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Effects of Ketorolac and α-tocopherol Combination on Formalin-induced Paw Edema in Rats",
            "journal": "Journal of Ad-Din Akij Medical College, 2(2), 19–24",
            "year": "2023",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Antibacterial Effect of Ginger (Zingiber officinale) against Pseudomonas aeruginosa",
            "journal": "Journal of Ad-Din Akij Medical College, 2(1), 19–28",
            "year": "2023",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Magnesium and Calcium Status in Autistic Spectrum Disorders (ASD): A Case-Control Study on Bangladeshi Children",
            "journal": "Journal of Ad-Din Akij Medical College, 2(1), 43–48",
            "year": "2023",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Evaluation of Breast Lesions by Fine Needle Aspiration Cytology in Bangladeshi Patients",
            "journal": "Journal of Ad-Din Akij Medical College, 1(1), 11–18",
            "year": "2022",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Morphological Study of Spleen among Adult Female Cadaver in Bangladesh",
            "journal": "Shahabuddin Medical College Journal, 6(2), 15–20",
            "year": "2022",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Relationship of High Sensitivity C-Reactive Protein Level to Anthropometric Parameters in Obese Children in a Tertiary Care Hospital in Bangladesh",
            "journal": "International Journal of Current Research, 13(5), 17240–17245",
            "year": "2021",
            "link": "https://doi.org/10.24941/ijcr.41285.05.2021",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Association of High-Sensitivity C-Reactive Protein Level with Central Obesity of the Children in a Tertiary Care Hospital of Bangladesh",
            "journal": "International Journal of Contemporary Pediatrics, 8(3), 407–413",
            "year": "2021",
            "link": "https://dx.doi.org/10.18203/2349-3291.ijcp20210645",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Plastination of Human Limb Sections in Bangladesh: Entering a New Era of Body Preservation",
            "journal": "Bangladesh Journal of Anatomy, 18(2), 47–54",
            "year": "2020",
            "link": "https://doi.org/10.3329/bja.v18i2.75557",
            "pdfDataUrl": "",
            "pdfName": ""
          }
        ]
      }
    ]
  },
  "apps": {
    "heading": {
      "en": "Apps",
      "bn": "অ্যাপস"
    },
    "subheading": {
      "en": "Apps I've built — view details, download, or buy.",
      "bn": "আমার তৈরি অ্যাপস — দেখুন, ডাউনলোড করুন বা কিনুন।"
    },
    "items": [
      {
        "icon": "images/app-icon-placeholder.svg",
        "name": "Sample App Name",
        "tagline": "One line describing what this app does.",
        "platform": "Android",
        "price": "Free",
        "rating": 4.5,
        "ratingCount": "120 reviews",
        "primaryCtaLabel": "Get on Play Store",
        "primaryCtaUrl": "#",
        "secondaryCtaLabel": "",
        "secondaryCtaUrl": ""
      }
    ]
  },
  "journey": {
    "heading": {
      "en": "Journey",
      "bn": "যাত্রা"
    },
    "subheading": {
      "en": "Career milestones",
      "bn": "ক্যারিয়ারের মাইলফলক"
    },
    "items": [
      {
        "year": "2025",
        "title": "Associate Professor (Anatomy)",
        "description": "Ad-din Akij Medical College — Teaching, dissection, and research. (Apr 2025 – present)",
        "category": "Career",
        "highlight": true
      },
      {
        "year": "2023",
        "title": "Assistant Editor, Journal Committee",
        "description": "Ad-din Akij Medical College — Reviewing, editing, and furnishing research papers. (Mar 2023 – present)",
        "category": "Career",
        "highlight": false
      },
      {
        "year": "2022",
        "title": "Member Secretary, Integrated Teaching Unit",
        "description": "Ad-din Akij Medical College — Arranging and conducting integrated teaching sessions for Phase-I MBBS students. (Dec 2022 – present)",
        "category": "Career",
        "highlight": false
      },
      {
        "year": "2021",
        "title": "Assistant Professor (Anatomy)",
        "description": "Ad-din Akij Medical College — Teaching, dissection, and research. (Jan 2021 – Apr 2025)",
        "category": "Career",
        "highlight": false
      },
      {
        "year": "2020",
        "title": "MS in Anatomy",
        "description": "Bangabandhu Sheikh Mujib Medical University (BSMMU).",
        "category": "Education",
        "highlight": true
      },
      {
        "year": "2017",
        "title": "Resident (Anatomy)",
        "description": "Bangabandhu Sheikh Mujib Medical University — Research, dissection, and teaching. (Mar 2017 – Mar 2020)",
        "category": "Career",
        "highlight": false
      },
      {
        "year": "2016",
        "title": "Lecturer (Anatomy)",
        "description": "Basundhara Ad-din Medical College — Teaching and dissection. (Jan 2016 – Feb 2017)",
        "category": "Career",
        "highlight": false
      },
      {
        "year": "2013",
        "title": "Medical Officer (Pediatrics)",
        "description": "Jahurul Islam Medical College — Managing indoor and outdoor pediatric cases. (Dec 2013 – Jan 2016)",
        "category": "Career",
        "highlight": false
      },
      {
        "year": "2012",
        "title": "MBBS",
        "description": "Jahurul Islam Medical College, Dhaka University.",
        "category": "Education",
        "highlight": true
      }
    ]
  },
  "testimonials": {
    "heading": {
      "en": "Testimonials",
      "bn": "মতামত"
    },
    "subheading": {
      "en": "What colleagues and students say",
      "bn": "সহকর্মী ও শিক্ষার্থীদের মতামত"
    },
    "items": [],
    "formHeading": {
      "en": "Share your feedback",
      "bn": "আপনার মতামত জানান"
    },
    "formNote": {
      "en": "Your message comes straight to me — I'll review it and publish it here myself, so it may not appear immediately.",
      "bn": "আপনার বার্তা সরাসরি আমার কাছে আসবে — আমি দেখে অনুমোদনের পর এখানে প্রকাশ করব, তাই সাথে সাথে দেখা যাবে না।"
    }
  },
  "blog": {
    "heading": {
      "en": "Blog",
      "bn": "ব্লগ"
    },
    "subheading": {
      "en": "Notes and articles",
      "bn": "নোট ও নিবন্ধ"
    },
    "items": [
      {
        "title": "Sample Blog Post Title",
        "date": "2025-01-15",
        "cover": "",
        "excerpt": "A one or two sentence summary that shows on the card.",
        "content": "The full text of your post goes here. Write as many paragraphs as you like — separate paragraphs with a blank line.",
        "tags": [],
        "attachments": []
      }
    ]
  },
  "faq": {
    "heading": {
      "en": "FAQ",
      "bn": "প্রশ্নোত্তর"
    },
    "subheading": {
      "en": "Common questions",
      "bn": "সাধারণ প্রশ্ন"
    },
    "items": [
      {
        "q": "Are you available for guest lectures or workshops?",
        "a": "Yes — please reach out through the contact section with details of the event."
      },
      {
        "q": "How can I access your publications?",
        "a": "Each publication has a download button where a PDF has been provided, or a link (including DOI) to the original source."
      },
      {
        "q": "Do you take on research collaborations?",
        "a": "Yes, particularly in anatomy, histology, and pediatric research — feel free to get in touch."
      }
    ]
  },
  "gallery": {
    "heading": {
      "en": "Gallery",
      "bn": "গ্যালারি"
    },
    "subheading": {
      "en": "Photos from work, conferences, and events",
      "bn": "কাজ, সম্মেলন ও অনুষ্ঠানের ছবি"
    },
    "categories": [
      {
        "id": "clinic",
        "label": "Clinic",
        "images": [
          {
            "src": "images/gallery-1.svg",
            "caption": "At the clinic"
          },
          {
            "src": "images/gallery-2.svg",
            "caption": "With the team"
          }
        ]
      },
      {
        "id": "conferences",
        "label": "Conferences",
        "images": [
          {
            "src": "images/gallery-3.svg",
            "caption": "Speaking at a conference"
          }
        ]
      }
    ]
  },
  "contact": {
    "heading": {
      "en": "Contact",
      "bn": "যোগাযোগ"
    },
    "subheading": {
      "en": "Feel free to reach out for collaborations, guest lectures, or questions.",
      "bn": "সহযোগিতা, অতিথি বক্তৃতা বা যেকোনো প্রশ্নের জন্য যোগাযোগ করুন।"
    },
    "emails": [
      {
        "icon": "📧",
        "label": "Personal Email",
        "value": "masudj16@gmail.com"
      },
      {
        "icon": "📧",
        "label": "Work Email",
        "value": "mm_rahman@addinmedical.org"
      }
    ],
    "phone": "+880 1914-128747",
    "location": "House 319, Road 3, Phase 2, Shonadanga, Khulna-9100, Bangladesh",
    "links": [
      {
        "icon": "🔬",
        "label": "ResearchGate",
        "url": "https://www.researchgate.net/profile/Moshiur-Rahman-54"
      },
      {
        "icon": "🎓",
        "label": "ORCID",
        "url": "https://orcid.org/0009-0003-3666-3746"
      },
      {
        "icon": "📚",
        "label": "Academia.edu",
        "url": "https://bsmmu.academia.edu/moshiurmasud"
      },
      {
        "icon": "🔗",
        "label": "ScienceOpen",
        "url": "https://www.scienceopen.com/user/f012a09b-d7a6-4cec-a5f2-7368695bb593"
      }
    ]
  },
  "customSections": []
};
