/*
  CONTENT.JS — generated by admin.html
  Upload this file into the js/ folder of your GitHub repo, replacing the old one.
*/

const SITE_CONTENT = {
  "site": {
    "name": "Moshiur Masud",
    "initials": "YN",
    "tagline": "Doctor | Medical Educator | Tech-freak Thinker",
    "footerNote": "Built with curisity ",
    "theme": "forest-copper",
    "fontPreset": "theme-default"
  },
  "nav": [
    {
      "label": "Home",
      "href": "#home"
    },
    {
      "label": "About",
      "href": "#about"
    },
    {
      "label": "Publications",
      "href": "#publications"
    },
    {
      "label": "Gallery",
      "href": "#gallery"
    },
    {
      "label": "Contact",
      "href": "#contact"
    }
  ],
  "hero": {
    "eyebrow": "Assalamu 'alaa Manittaba'al Hudaa",
    "name": "Md. Moshiur Rahman",
    "role": "MBBS, MS - Anatomy",
    "tagline": "A doctor, medical educator and technology enthusiast exploring the intersection of healthcare, knowledge and digital innovation.",
    "ctaLabel": "Get in touch",
    "ctaHref": "#contact",
    "photo": "images/profile.svg",
    "status": "Available",
    "badges": [
      {
        "icon": "🩺",
        "label": "Physician"
      },
      {
        "icon": "🔬",
        "label": "Researcher"
      },
      {
        "icon": "📚",
        "label": "Educator"
      },
      {
        "icon": "✨",
        "label": "Techy"
      }
    ]
  },
  "about": {
    "heading": "About",
    "paragraphs": [
      "A research-driven anatomist and academic educator, holding a Master of Science in Anatomy, with expertise spanning research methodology, biostatistics, histology, plastination, and genetic laboratory methodologies. Committed to advancing anatomical sciences through evidence-based pedagogy and rigorous scholarly inquiry, with a particular focus on developing innovative curricula that bridge classical morphological sciences and contemporary biomedical practice.",
      "",
      "This site brings together my background, publications, and moments from my work — feel free to reach out."
    ],
    "photo": "images/about.svg",
    "stats": [
      {
        "value": "10+",
        "label": "Years in practice"
      },
      {
        "value": "12+",
        "label": "Publications"
      },
      {
        "value": "5",
        "label": "Hospitals worked with"
      }
    ],
    "credentials": [
      "MBBS — Jahurul Islam Medical College",
      "MS, Anatomy — Bangladesh Medical University",
      "Life Member, Anatomical Society of Bangladesh"
    ]
  },
  "publications": {
    "heading": "Publications",
    "subheading": "Research papers, articles, and case studies",
    "categories": [
      {
        "id": "research",
        "label": "Research Papers",
        "items": [
          {
            "title": "Sample Research Paper Title Goes Here",
            "journal": "Journal of Example Medicine",
            "year": "2024",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Another Research Paper Title",
            "journal": "Bangladesh Journal of Medicine",
            "year": "2023",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          }
        ]
      }
    ]
  },
  "gallery": {
    "heading": "Gallery",
    "subheading": "Photos from work, conferences, and events",
    "categories": [
      {
        "id": "clinic",
        "label": "Clinic",
        "images": [
          {
            "src": "images/gallery-1.svg",
            "caption": "At the clinic"
          },
          {
            "src": "images/gallery-2.svg",
            "caption": "With the team"
          }
        ]
      },
      {
        "id": "conferences",
        "label": "Conferences",
        "images": [
          {
            "src": "images/gallery-3.svg",
            "caption": "Speaking at a conference"
          }
        ]
      },
      {
        "id": "cat1787384226291",
        "label": "A journey of curiosity.....",
        "images": [
          {
            "src": "images/new-photo.jpg",
            "caption": "Caption here"
          }
        ]
      }
    ]
  },
  "contact": {
    "heading": "Contact",
    "subheading": "Feel free to reach out for consultations, collaborations, or questions.",
    "phone": "+880 1",
    "location": "Khulna, Bangladesh",
    "links": [
      {
        "label": "ORCID",
        "url": "https://orcid.org/0009-0003-3666-3746",
        "icon": "🔗"
      },
      {
        "label": "ResearchGate",
        "url": "https://www.researchgate.net/profile/Moshiur-Masud?ev=hdr_xprf",
        "icon": "🔗"
      },
      {
        "label": "Facebook",
        "url": "https://www.facebook.com/masud.jimch",
        "icon": "🔗"
      },
      {
        "label": "GitHub",
        "url": "https://github.com/masudjimch",
        "icon": "🔗"
      },
      {
        "label": "LinkedIn",
        "url": "https://www.linkedin.com/in/moshiur-masud-9868b253/",
        "icon": "🔗"
      },
      {
        "label": "Twitter / X",
        "url": "https://x.com/MasudJimch",
        "icon": "🔗"
      }
    ],
    "emails": [
      {
        "icon": "📧",
        "label": "Email",
        "value": "masudj16@gmail.com"
      }
    ]
  },
  "apps": {
    "heading": "Apps",
    "subheading": "Apps I've built — view details, download, or buy.",
    "items": []
  }
};
