/*
  CONTENT.JS — generated by admin.html
  Upload this file into the js/ folder of your GitHub repo, replacing the old one.
*/

const SITE_CONTENT = {
  "site": {
    "name": "Moshiur Masud",
    "initials": "YN",
    "tagline": "Doctor | Medical Educator | Tech-freak Thinker",
    "footerNote": "Built with curisity ",
    "theme": "teal-charcoal"
  },
  "nav": [
    {
      "label": "Home",
      "href": "#home"
    },
    {
      "label": "About",
      "href": "#about"
    },
    {
      "label": "Publications",
      "href": "#publications"
    },
    {
      "label": "Gallery",
      "href": "#gallery"
    },
    {
      "label": "Contact",
      "href": "#contact"
    }
  ],
  "hero": {
    "eyebrow": "Assalamu 'alaa Manittaba'al Hudaa",
    "name": "Md. Moshiur Rahman",
    "role": "MBBS, MS - Anatomy",
    "tagline": "",
    "ctaLabel": "Get in touch",
    "ctaHref": "#contact",
    "photo": "images/profile.svg",
    "status": "Available",
    "badges": [
      {
        "icon": "🩺",
        "label": "Physician"
      },
      {
        "icon": "🔬",
        "label": "Researcher"
      },
      {
        "icon": "📚",
        "label": "Educator"
      },
      {
        "icon": "✨",
        "label": "Techy"
      }
    ]
  },
  "about": {
    "heading": "About",
    "paragraphs": [
      "I am a physician based in Khulna, Bangladesh, focused on patient-centered care and clinical research.",
      "Over the years I have worked across hospital medicine, outpatient care, and community health programs, publishing research along the way.",
      "This site brings together my background, publications, and moments from my work — feel free to reach out."
    ],
    "photo": "images/about.svg",
    "stats": [
      {
        "value": "10+",
        "label": "Years in practice"
      },
      {
        "value": "20+",
        "label": "Publications"
      },
      {
        "value": "5",
        "label": "Hospitals worked with"
      }
    ],
    "credentials": [
      "MBBS — Jahurul Islam Medical College",
      "MS, Anatomy — Bangladesh Medical University",
      "Life Member, Anatomical Society of Bangladesh"
    ]
  },
  "publications": {
    "heading": "Publications",
    "subheading": "Research papers, articles, and case studies",
    "categories": [
      {
        "id": "research",
        "label": "Research Papers",
        "items": [
          {
            "title": "Sample Research Paper Title Goes Here",
            "journal": "Journal of Example Medicine",
            "year": "2024",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          },
          {
            "title": "Another Research Paper Title",
            "journal": "Bangladesh Journal of Medicine",
            "year": "2023",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          }
        ]
      },
      {
        "id": "articles",
        "label": "Articles",
        "items": [
          {
            "title": "Sample Article or Opinion Piece",
            "journal": "Health Magazine",
            "year": "2024",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          }
        ]
      },
      {
        "id": "cases",
        "label": "Case Studies",
        "items": [
          {
            "title": "Sample Case Study Title",
            "journal": "Clinical Case Reports",
            "year": "2022",
            "link": "#",
            "pdfDataUrl": "",
            "pdfName": ""
          }
        ]
      }
    ]
  },
  "gallery": {
    "heading": "Gallery",
    "subheading": "Photos from work, conferences, and events",
    "categories": [
      {
        "id": "clinic",
        "label": "Clinic",
        "images": [
          {
            "src": "images/gallery-1.svg",
            "caption": "At the clinic"
          },
          {
            "src": "images/gallery-2.svg",
            "caption": "With the team"
          }
        ]
      },
      {
        "id": "conferences",
        "label": "Conferences",
        "images": [
          {
            "src": "images/gallery-3.svg",
            "caption": "Speaking at a conference"
          }
        ]
      }
    ]
  },
  "contact": {
    "heading": "Contact",
    "subheading": "Feel free to reach out for consultations, collaborations, or questions.",
    "email": "your.email@example.com",
    "phone": "+880 1XXX-XXXXXX",
    "location": "Khulna, Bangladesh",
    "links": [
      {
        "label": "LinkedIn",
        "url": "https://linkedin.com/in/yourname"
      },
      {
        "label": "ResearchGate",
        "url": "https://researchgate.net/profile/yourname"
      },
      {
        "label": "Twitter / X",
        "url": "https://x.com/yourname"
      }
    ]
  }
};
